name: kroner_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_reactive_ble: ^5.2.0
  location_permissions: ^4.0.0
  audioplayers: ^0.19.1
  get: ^4.6.6
  provider: ^5.0.0

  

flutter:
  uses-material-design: true
  assets:
    - assets/datos.json
    - assets/beep.mov
